// <auto-generated />
using System;
using Demo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20261005174013_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Demo.Domain.Modules.ExchangeRates.ExchangeRate", b =>
                {
                    b.Property<long>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuoteCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.HasKey("SnapshotId", "QuoteCurrency");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("Demo.Domain.Modules.ExchangeRates.ExchangeRateSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RateTimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "BaseCurrency", "RateTimestampUtc")
                        .IsUnique();

                    b.ToTable("ExchangeRateSnapshots");
                });

            modelBuilder.Entity("Demo.Domain.Modules.ExchangeRates.LatestExchangeRate", b =>
                {
                    b.Property<string>("BaseCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("QuoteCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RateTimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("BaseCurrency", "QuoteCurrency");

                    b.HasIndex("SnapshotId");

                    b.ToTable("LatestExchangeRates");
                });

            modelBuilder.Entity("Demo.Domain.Modules.Inventory.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Sku");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Demo.Domain.Modules.ExchangeRates.ExchangeRate", b =>
                {
                    b.HasOne("Demo.Domain.Modules.ExchangeRates.ExchangeRateSnapshot", null)
                        .WithMany("Rates")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Demo.Domain.Modules.ExchangeRates.LatestExchangeRate", b =>
                {
                    b.HasOne("Demo.Domain.Modules.ExchangeRates.ExchangeRateSnapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Demo.Domain.Modules.ExchangeRates.ExchangeRateSnapshot", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
